// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/scope.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Scope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,5,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	DeletedAt     string                 `protobuf:"bytes,6,opt,name=DeletedAt,proto3" json:"DeletedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scope) Reset() {
	*x = Scope{}
	mi := &file_proto_scope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scope) ProtoMessage() {}

func (x *Scope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scope.ProtoReflect.Descriptor instead.
func (*Scope) Descriptor() ([]byte, []int) {
	return file_proto_scope_proto_rawDescGZIP(), []int{0}
}

func (x *Scope) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Scope) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Scope) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Scope) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Scope) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Scope) GetDeletedAt() string {
	if x != nil {
		return x.DeletedAt
	}
	return ""
}

type CreateScopeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateScopeRequest) Reset() {
	*x = CreateScopeRequest{}
	mi := &file_proto_scope_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateScopeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateScopeRequest) ProtoMessage() {}

func (x *CreateScopeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scope_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateScopeRequest.ProtoReflect.Descriptor instead.
func (*CreateScopeRequest) Descriptor() ([]byte, []int) {
	return file_proto_scope_proto_rawDescGZIP(), []int{1}
}

func (x *CreateScopeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateScopeRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type GetScopeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScopeRequest) Reset() {
	*x = GetScopeRequest{}
	mi := &file_proto_scope_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScopeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScopeRequest) ProtoMessage() {}

func (x *GetScopeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scope_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScopeRequest.ProtoReflect.Descriptor instead.
func (*GetScopeRequest) Descriptor() ([]byte, []int) {
	return file_proto_scope_proto_rawDescGZIP(), []int{2}
}

func (x *GetScopeRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListScopeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListScopeRequest) Reset() {
	*x = ListScopeRequest{}
	mi := &file_proto_scope_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScopeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScopeRequest) ProtoMessage() {}

func (x *ListScopeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scope_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScopeRequest.ProtoReflect.Descriptor instead.
func (*ListScopeRequest) Descriptor() ([]byte, []int) {
	return file_proto_scope_proto_rawDescGZIP(), []int{3}
}

type UpdateScopeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateScopeRequest) Reset() {
	*x = UpdateScopeRequest{}
	mi := &file_proto_scope_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateScopeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateScopeRequest) ProtoMessage() {}

func (x *UpdateScopeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scope_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateScopeRequest.ProtoReflect.Descriptor instead.
func (*UpdateScopeRequest) Descriptor() ([]byte, []int) {
	return file_proto_scope_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateScopeRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateScopeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateScopeRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type DeleteScopeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteScopeRequest) Reset() {
	*x = DeleteScopeRequest{}
	mi := &file_proto_scope_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteScopeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteScopeRequest) ProtoMessage() {}

func (x *DeleteScopeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scope_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteScopeRequest.ProtoReflect.Descriptor instead.
func (*DeleteScopeRequest) Descriptor() ([]byte, []int) {
	return file_proto_scope_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteScopeRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ScopeResponseBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         *Scope                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScopeResponseBody) Reset() {
	*x = ScopeResponseBody{}
	mi := &file_proto_scope_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScopeResponseBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScopeResponseBody) ProtoMessage() {}

func (x *ScopeResponseBody) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scope_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScopeResponseBody.ProtoReflect.Descriptor instead.
func (*ScopeResponseBody) Descriptor() ([]byte, []int) {
	return file_proto_scope_proto_rawDescGZIP(), []int{6}
}

func (x *ScopeResponseBody) GetScope() *Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

type ScopeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Body          *ScopeResponseBody     `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScopeResponse) Reset() {
	*x = ScopeResponse{}
	mi := &file_proto_scope_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScopeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScopeResponse) ProtoMessage() {}

func (x *ScopeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scope_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScopeResponse.ProtoReflect.Descriptor instead.
func (*ScopeResponse) Descriptor() ([]byte, []int) {
	return file_proto_scope_proto_rawDescGZIP(), []int{7}
}

func (x *ScopeResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ScopeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ScopeResponse) GetBody() *ScopeResponseBody {
	if x != nil {
		return x.Body
	}
	return nil
}

type ListScopeResponseBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scopes        []*Scope               `protobuf:"bytes,1,rep,name=scopes,proto3" json:"scopes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListScopeResponseBody) Reset() {
	*x = ListScopeResponseBody{}
	mi := &file_proto_scope_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScopeResponseBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScopeResponseBody) ProtoMessage() {}

func (x *ListScopeResponseBody) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scope_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScopeResponseBody.ProtoReflect.Descriptor instead.
func (*ListScopeResponseBody) Descriptor() ([]byte, []int) {
	return file_proto_scope_proto_rawDescGZIP(), []int{8}
}

func (x *ListScopeResponseBody) GetScopes() []*Scope {
	if x != nil {
		return x.Scopes
	}
	return nil
}

type ListScopeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Body          *ListScopeResponseBody `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListScopeResponse) Reset() {
	*x = ListScopeResponse{}
	mi := &file_proto_scope_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScopeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScopeResponse) ProtoMessage() {}

func (x *ListScopeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scope_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScopeResponse.ProtoReflect.Descriptor instead.
func (*ListScopeResponse) Descriptor() ([]byte, []int) {
	return file_proto_scope_proto_rawDescGZIP(), []int{9}
}

func (x *ListScopeResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ListScopeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListScopeResponse) GetBody() *ListScopeResponseBody {
	if x != nil {
		return x.Body
	}
	return nil
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_proto_scope_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scope_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_scope_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *DeleteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_scope_proto protoreflect.FileDescriptor

const file_proto_scope_proto_rawDesc = "" +
	"\n" +
	"\x11proto/scope.proto\x12\x05proto\"\xa7\x01\n" +
	"\x05Scope\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1c\n" +
	"\tCreatedAt\x18\x04 \x01(\tR\tCreatedAt\x12\x1c\n" +
	"\tUpdatedAt\x18\x05 \x01(\tR\tUpdatedAt\x12\x1c\n" +
	"\tDeletedAt\x18\x06 \x01(\tR\tDeletedAt\"J\n" +
	"\x12CreateScopeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"!\n" +
	"\x0fGetScopeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x12\n" +
	"\x10ListScopeRequest\"Z\n" +
	"\x12UpdateScopeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"$\n" +
	"\x12DeleteScopeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"7\n" +
	"\x11ScopeResponseBody\x12\"\n" +
	"\x05scope\x18\x01 \x01(\v2\f.proto.ScopeR\x05scope\"w\n" +
	"\rScopeResponse\x12\x1e\n" +
	"\n" +
	"statusCode\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12,\n" +
	"\x04body\x18\x03 \x01(\v2\x18.proto.ScopeResponseBodyR\x04body\"=\n" +
	"\x15ListScopeResponseBody\x12$\n" +
	"\x06scopes\x18\x01 \x03(\v2\f.proto.ScopeR\x06scopes\"\x7f\n" +
	"\x11ListScopeResponse\x12\x1e\n" +
	"\n" +
	"statusCode\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x120\n" +
	"\x04body\x18\x03 \x01(\v2\x1c.proto.ListScopeResponseBodyR\x04body\"J\n" +
	"\x0eDeleteResponse\x12\x1e\n" +
	"\n" +
	"statusCode\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xc9\x02\n" +
	"\fScopeService\x12>\n" +
	"\vCreateScope\x12\x19.proto.CreateScopeRequest\x1a\x14.proto.ScopeResponse\x128\n" +
	"\bGetScope\x12\x16.proto.GetScopeRequest\x1a\x14.proto.ScopeResponse\x12>\n" +
	"\tListScope\x12\x17.proto.ListScopeRequest\x1a\x18.proto.ListScopeResponse\x12>\n" +
	"\vUpdateScope\x12\x19.proto.UpdateScopeRequest\x1a\x14.proto.ScopeResponse\x12?\n" +
	"\vDeleteScope\x12\x19.proto.DeleteScopeRequest\x1a\x15.proto.DeleteResponseB\bZ\x06/protob\x06proto3"

var (
	file_proto_scope_proto_rawDescOnce sync.Once
	file_proto_scope_proto_rawDescData []byte
)

func file_proto_scope_proto_rawDescGZIP() []byte {
	file_proto_scope_proto_rawDescOnce.Do(func() {
		file_proto_scope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_scope_proto_rawDesc), len(file_proto_scope_proto_rawDesc)))
	})
	return file_proto_scope_proto_rawDescData
}

var file_proto_scope_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_scope_proto_goTypes = []any{
	(*Scope)(nil),                 // 0: proto.Scope
	(*CreateScopeRequest)(nil),    // 1: proto.CreateScopeRequest
	(*GetScopeRequest)(nil),       // 2: proto.GetScopeRequest
	(*ListScopeRequest)(nil),      // 3: proto.ListScopeRequest
	(*UpdateScopeRequest)(nil),    // 4: proto.UpdateScopeRequest
	(*DeleteScopeRequest)(nil),    // 5: proto.DeleteScopeRequest
	(*ScopeResponseBody)(nil),     // 6: proto.ScopeResponseBody
	(*ScopeResponse)(nil),         // 7: proto.ScopeResponse
	(*ListScopeResponseBody)(nil), // 8: proto.ListScopeResponseBody
	(*ListScopeResponse)(nil),     // 9: proto.ListScopeResponse
	(*DeleteResponse)(nil),        // 10: proto.DeleteResponse
}
var file_proto_scope_proto_depIdxs = []int32{
	0,  // 0: proto.ScopeResponseBody.scope:type_name -> proto.Scope
	6,  // 1: proto.ScopeResponse.body:type_name -> proto.ScopeResponseBody
	0,  // 2: proto.ListScopeResponseBody.scopes:type_name -> proto.Scope
	8,  // 3: proto.ListScopeResponse.body:type_name -> proto.ListScopeResponseBody
	1,  // 4: proto.ScopeService.CreateScope:input_type -> proto.CreateScopeRequest
	2,  // 5: proto.ScopeService.GetScope:input_type -> proto.GetScopeRequest
	3,  // 6: proto.ScopeService.ListScope:input_type -> proto.ListScopeRequest
	4,  // 7: proto.ScopeService.UpdateScope:input_type -> proto.UpdateScopeRequest
	5,  // 8: proto.ScopeService.DeleteScope:input_type -> proto.DeleteScopeRequest
	7,  // 9: proto.ScopeService.CreateScope:output_type -> proto.ScopeResponse
	7,  // 10: proto.ScopeService.GetScope:output_type -> proto.ScopeResponse
	9,  // 11: proto.ScopeService.ListScope:output_type -> proto.ListScopeResponse
	7,  // 12: proto.ScopeService.UpdateScope:output_type -> proto.ScopeResponse
	10, // 13: proto.ScopeService.DeleteScope:output_type -> proto.DeleteResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_scope_proto_init() }
func file_proto_scope_proto_init() {
	if File_proto_scope_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_scope_proto_rawDesc), len(file_proto_scope_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_scope_proto_goTypes,
		DependencyIndexes: file_proto_scope_proto_depIdxs,
		MessageInfos:      file_proto_scope_proto_msgTypes,
	}.Build()
	File_proto_scope_proto = out.File
	file_proto_scope_proto_goTypes = nil
	file_proto_scope_proto_depIdxs = nil
}
